name: Documentation Improvement
description: Suggest improvements to documentation
title: "[Docs]: "
labels: ["docs"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation! Suggest fixes, additions, or clarifications.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What kind of documentation needs improvement?
      options:
        - API Reference
        - User Guide/Tutorial
        - Architecture Documentation
        - README
        - Code Comments
        - Contributing Guide
        - Other
    validations:
      required: true

  - type: input
    id: doc-location
    attributes:
      label: Documentation Location
      description: File path or URL of the documentation
      placeholder: "docs/guides/getting-started.md or https://..."
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What's wrong with the current documentation?
      options:
        - Missing information
        - Incorrect/outdated information
        - Unclear explanation
        - Typo/grammar
        - Broken link
        - Missing example
        - Code example doesn't work
        - Other
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Content
      description: Quote the problematic section (if applicable)
      render: markdown
      placeholder: |
        > Current text that needs improvement
    validations:
      required: false

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe what's wrong or missing
      placeholder: What needs to be fixed or added?
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How should it be improved?
      placeholder: Proposed new or updated content
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Screenshots, related docs, examples, etc.
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help fix this?
      options:
        - label: I can submit a PR with the fix
        - label: I need help from the maintainers
